on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: make a directory
        run: mkdir -p deploy

      - name: copy build files  #
        run: cp -r build/* ./deploy

      - name: copy appspec.yml, deploy.sh
        run: cp -r appspec.yml deploy.sh ./deploy

      - name: make zip file
        run: zip -r ./deploy.zip ./deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://diary-front/deploy.zip

      - name: deploy
        run: |
          aws deploy create-deployment \
          --application-name diary-front-codedeploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name diary-front-codedeploy-deploygroup \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=diary-front,bundleType=zip,key=deploy.zip \